name: zencillo_credibanco
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  oxidized: ^6.2.0
  plugin_platform_interface: ^2.0.2
  zencillo_helpers:
    git:
      url: https://github.com/andyguzmanZencillo/zencillo_helpers.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.zencillo_credibanco
        pluginClass: ZencilloCredibancoPlugin
      ios:
        pluginClass: ZencilloCredibancoPlugin
